const projetos = [
    {
        nome: "Projeto Residencial Vila Nova",
        email: "maria@exemplo.com",
        tipoProjeto: "Projeto Residencial",
        id: "#231",
        tipoConta: "Pro",
        dataInicio: "28-12-2023 13:30",
        dataFim: "15-01-2024 14:30",
        statusProjeto: "Concluído",
        descricao: "projeto elétrico Residencial Vila Nova",
    },
    {
        nome: "ProjetoComercial EnerCheck Jaketa",
        email: "joao@exemplo.com",
        tipoProjeto: "Projeto Comercial",
        id: "#323",
        tipoConta: "Básico",
        dataInicio: "15-01-2024 14:25",
        dataFim: "Não concluído",
        statusProjeto: "Processando",
        descricao: "projeto elétrico Jaketa",
    },
    {
        nome: "Projeto Industrial PlastBras EnerCheck",
        email: "ana@exemplo.com",
        tipoProjeto: "Projeto Industrial",
        id: "#123",
        tipoConta: "Empresas",
        dataInicio: "28-12-2023 07:30",
        dataFim: "05-01-2024 16:45",
        statusProjeto: "Concluído",
        descricao: "projeto elétrico industrial PlastBras",
    },
    {
        nome: "Projeto Residencial Centro",
        email: "carlos@exemplo.com",
        tipoProjeto: "Projeto Residencial",
        id: "#456",
        tipoConta: "Pro",
        dataInicio: "10-01-2024 09:15",
        dataFim: "Não concluído",
        statusProjeto: "Erro",
        descricao: "projeto elétrico residencial centro da cidade",
    },
    {
        nome: "Projeto Comercial Shopping",
        email: "lucia@exemplo.com",
        tipoProjeto: "Projeto Comercial",
        id: "#789",
        tipoConta: "Empresas",
        dataInicio: "20-01-2024 11:00",
        dataFim: "Não concluído",
        statusProjeto: "Processando",
        descricao: "projeto elétrico para shopping center",
    }
];

export default projetos;